<?php $this->declareVars('exchangeRates', 'exchangeRatesCount', 'activeShoppingCartCurrency') ?>
<?php $this->exchangeRates = $this->paymentCurrency()->getExchangeRates(true) ?>
<?php $this->exchangeRatesCount = count($this->exchangeRates) ?>
<?php $this->activeShoppingCartCurrency = $this->paymentCurrency()->getActiveShoppingCartCurrency() ?>

<div id="shopping-cart-wrapper" style="visibility: hidden">        
    <div id="shopping-cart-info">
        <h5>
            <b><?php echo $this->translate('Shopping cart') ?></b>
            <?php if ($this->paymentShoppingCart()->getItemsCount()) : ?>
                <?php echo sprintf($this->translate('Shopping cart info'), $this->paymentShoppingCart()->getItemsCount(), $this->paymentProcessCost($this->paymentShoppingCart()->getItemsDiscountedAmount(), true)) ?>
                <?php if ($this->paymentShoppingCart()->getCurrentDiscount()) : ?>
                    <?php echo $this->translate('discount') ?>: <?php echo $this->escapeHtml($this->paymentShoppingCart()->getCurrentDiscount()) ?>%
                <?php endif ?>
             <?php endif ?>
        </h5>
        <?php if ($this->paymentShoppingCart()->getItemsCount()): ?>
            <a href="<?php echo  $this->url('page', ['page_name' => $this->pageUrl('shopping-cart')], ['force_canonical' => true]) ?>">
                <?php echo $this->translate('View the shopping cart') ?>
            </a> |
            <a rel="nofollow" href="javascript:void(0)" onclick="payment.cleanShoppingCart(<?php if (true === $this->is_shopping_cart_page): ?>true<?php endif ?>)">
                <?php echo $this->translate('Clean the shopping cart') ?>
            </a>
        <?php else: ?>
            <?php echo $this->translate('Shopping cart is empty') ?>
        <?php endif ?>
    </div>
    <?php if ($this->exchangeRatesCount) : ?>
        <div id="shopping-cart-currencies">
            <h5><b><?php echo $this->translate('Currency') ?></b></h5>
            <?php foreach ($this->exchangeRates as $currency) : ?>
                <?php $this->i++ ?>
                
                <?php if ($currency['code'] == $this->activeShoppingCartCurrency) : ?>
                    <span><?php echo $this->escapeHtml($currency['code']) ?></span>
                <?php else: ?>
                    <a rel="nofollow" href="javascript:void(0)" onclick="payment.changeCurrency('<?php echo $this->escapeJs($currency['code']) ?>')"><?php echo $this->escapeHtml($currency['code']) ?></a>
                <?php endif ?>

                <?php if ($this->i < $this->exchangeRatesCount) : ?>
                |
                <?php endif; ?>

            <?php endforeach ?>
        </div>
    <?php endif ?>
    <div class="clearfix"></div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        var $wrapper = $("#shopping-cart-wrapper");
        var $wrapperHeader = $wrapper.find("#shopping-cart-info");
        var wrapperHeight = $wrapper.outerHeight(true) - $wrapperHeader.outerHeight(true);

        // set wrapper position
        $wrapper.css("bottom", -wrapperHeight).css("visibility", "visible");

        $wrapper.click(function() {
            if ($(this).hasClass("expandedShoppingCart")) {
                hideWrapper();
            }
            else {        
                showWrapper();
            }
        }); 

        /**
         * Show wrapper
         *
         * @return void
         */
        function showWrapper()
        {
            $wrapper.find("a").on("click", function(e) {
                e.preventDefault;
            });

            $wrapper.animate({
                bottom: 0
            }, function() {
                $(this).addClass("expandedShoppingCart");
                $wrapper.find("a").unbind();
            });
        }

        /**
         * Hide wrapper
         * 
         * @return void
         */
        function hideWrapper()
        {
            $wrapper.animate({
                bottom: -wrapperHeight
            }, function() {
                $(this).removeClass("expandedShoppingCart");
            });
        }
    });
</script>