<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of discount coupons') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'coupons' // selected action is "coupons"
]) ?>

<!-- render a data grid -->
<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'payments-administration',
    'action' => 'coupons',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('Code'),
            'order_name' => 'slug'
        ],
        [
            'title' => $this->translate('Discount'),
            'order_name' => 'discount'
        ],
        [
            'title' => $this->translate('Used'),
            'order_name' => 'used'
        ],
        [
            'title' => $this->translate('Activation date'),
            'order_name' => 'start'
        ],
        [
            'title' => $this->translate('Deactivation date'),
            'order_name' => 'end'
        ]
    ],
    'paginator' => $this->paginator,
    'helpers' => [
        'discount' => 'numberFormat',
        'used' => 'applicationBooleanValue',
        'start' => 'applicationDate',
        'end' => 'applicationDate'
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
            [
                'name' => $this->translate('Add a coupon'),
                'controller' => 'payments-administration',
                'action' => 'add-coupon',
                'check_acl' => true
            ]
        ],
        'multiple_actions' => [
            [
                'name' => $this->translate('Delete selected'),
                'controller' => 'payments-administration',
                'action' => 'delete-coupons',
                'check_acl' => true,
                'confirm' => $this->translate('Selected coupons will be deleted. Are you sure?')
            ]
        ],
        'single_actions' => [
            [
                'name' => $this->translate('Edit the coupon'),
                'controller' => 'payments-administration',
                'action' => 'edit-coupon',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/edit_action.png', 'image')
            ]
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'coupons',
        'multiple_actions' => [
            'items_name' => 'coupons[]'
        ]
    ],
    'actions_extra_check' => [
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Discount coupons'),
    'body' => $this->content
]) ?>