<?php use Payment\Model\PaymentBase as PaymentBaseModel ?>

<?php $this->declareVars('subPageTitle', 'parentPageTitle') ?>

<?php $this->subPageTitle = $this->translate('Edit the currency') ?>
<?php $this->parentPageTitle = $this->translate('List of currencies') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'currencies' // selected action is "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'currencies' => [
            'name' => $this->parentPageTitle,
            'controller' => 'payments-administration',
            'action' => 'currencies',
            'check_acl' => true
        ],
        'add_currency' => [
            'name' => $this->subPageTitle,
            'controller' => 'payments-administration',
            'action' => 'edit-currency',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'payments-administration',
        'action' => 'delete-currencies',
        'name' => $this->translate('Delete the currency'),
        'check_acl' => true,
        'hide_action' => PaymentBaseModel::PRIMARY_CURRENCY == $this->currency['primary_currency'],
        'confirm' => $this->translate('Currency will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'currencies' : [{$this->currency['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'payments-administration', 'action' => 'currencies'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'payments-administration',
        'action' => 'edit-exchange-rates',
        'params' => [
            'slug' => $this->currency['id']
        ],
        'name' => $this->translate('Exchange rates'),
        'check_acl' => true,
        'hide_action' => PaymentBaseModel::PRIMARY_CURRENCY != $this->currency['primary_currency'],
    ],
    [
        'controller' => 'payments-administration',
        'action' => 'add-currency',
        'name' => $this->translate('Add a currency'),
        'check_acl' => true
    ]]
]))
?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-8">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Editing'),
                'body' => $this->partial('partial/form', [
                    'form' => $this->currency_form,
                    'controller' => 'payments-administration',
                    'action' => 'edit-currency',
                    'params' => [
                        'slug' => $this->currency['id']
                    ]
                ])
            ]) ?>
        </div>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <!-- render a form -->
            <?php echo $this->partial('administration-partial/panel', [
                'notification' => false,
                'title' => $this->translate('Editing'),
                'body' => $this->partial('partial/form', [
                    'form' => $this->currency_form,
                    'controller' => 'payments-administration',
                    'action' => 'edit-currency',
                    'params' => [
                        'slug' => $this->currency['id']
                    ]
                ])
            ]) ?>
        </div>
    <?php endif ?>
</div>