<?php $this->declareVars('subPageTitle', 'content') ?>
<?php $this->subPageTitle = $this->translate('List of transactions') ?>
<?php $this->headTitle($this->subPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is "list"
]) ?>

<!-- render a data grid -->
<?php $this->content = $this->partial('partial/data-grid', [
    'controller' => 'payments-administration',
    'action' => 'list',
    'order_by' => $this->order_by,
    'order_type' => $this->order_type,
    'per_page' => $this->per_page,
    'default_order' => 'id',
    'default_order_type' => 'desc',
    'filter_form' => $this->filter_form,
    'headers' => [
        [
            'title' => $this->translate('ID'),
            'order_name' => 'id'
        ],
        [
            'title' => $this->translate('Code'),
            'order_name' => 'slug'
        ],
        [
            'title' => $this->translate('Paid'),
            'order_name' => 'paid'
        ],
        [
            'title' => $this->translate('Email'),
            'order_name' => 'email'
        ],
        [
            'title' => $this->translate('Total amount'),
            'order_name' => 'cost'
        ],
        [
            'title' => $this->translate('Date'),
            'order_name' => 'date'
        ]
    ],
    'paginator' => $this->paginator,
    'skipped_fields' => [
        'currency'
    ],
    'helpers' => [
        'paid' => 'applicationBooleanValue',
        'cost' => 'paymentCostFormat',
        'date' => 'applicationDate',
        'payment' => 'translate',
    ],
    'helpers_set_array' => [
        'cost' => true
    ],
    'helpers_options' => [
    ],
    'actions' => [
        'regular_actions' => [
        ],
        'multiple_actions' => [
            [
                'name' => $this->translate('Delete selected'),
                'controller' => 'payments-administration',
                'action' => 'delete-transactions',
                'check_acl' => true,
                'confirm' => $this->translate('Selected transactions will be deleted. Are you sure?')
            ],
            [
                'name' => $this->translate('Activate selected'),
                'controller' => 'payments-administration',
                'action' => 'activate-transactions',
                'check_acl' => true
            ]
        ],
        'single_actions' => [
            [
                'name' => $this->translate('View the transaction\'s details'),
                'controller' => 'payments-administration',
                'action' => 'view-transaction-details',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/view_details_action.png', 'image', 'payment')
            ],
            [
                'name' => $this->translate('View the transaction\'s items'),
                'controller' => 'payments-administration',
                'action' => 'view-transaction-items',
                'check_acl' => true,
                'image' => $this->layoutAsset('icon/browse_items.png', 'image', 'payment')
            ],
        ]
    ],
    'actions_options' => [
        'action_identity' => 'id',
        'form_name' => 'transactions',
        'multiple_actions' => [
            'items_name' => 'transactions[]'
        ]
    ],
    'actions_extra_check' => [
    ]
]) ?>

<!-- render a data grid -->
<?php echo $this->partial('administration-partial/panel', [
    'title' => $this->translate('Transactions'),
    'body' => $this->content
]) ?>