<?php $this->declareVars('subPageTitle', 'parentPageTitle', 'content') ?>

<?php $this->subPageTitle = $this->translate('View the transaction\'s details') ?>
<?php $this->parentPageTitle = $this->translate('List of transactions') ?>

<?php $this->headTitle($this->subPageTitle) ?>
<?php $this->headTitle($this->transaction['slug']) ?>
<?php $this->headTitle($this->parentPageTitle) ?>

<!-- render a header -->
<?php echo $this->render('payment/payment-administration/_header') ?>

<!-- render tabs -->
<?php echo $this->partial('administration-partial/tab', [
    'tabs' => $this->baseTabs,
    'active' => 'list' // selected action is the "list"
]) ?>

<!-- render a breadcrumb -->
<?php echo $this->partial('administration-partial/breadcrumb', [
    'pages' => [
        'list' => [
            'name' => $this->parentPageTitle,
            'controller' => 'payments-administration',
            'action' => 'list',
            'check_acl' => true
        ],
        'view_details' => [
            'name' => $this->transaction['slug'] . ' - ' . $this->subPageTitle,
            'controller' => 'payments-administration',
            'action' => 'view-transaction-details',
            'check_acl' => true
        ]
    ]
]) ?>

<?php $this->extraActions = trim($this->partial('administration-partial/extra-actions', ['pages' => [
    [
        'controller' => 'payments-administration',
        'action' => 'delete-transactions',
        'name' => $this->translate('Delete the transaction'),
        'check_acl' => true,
        'confirm' => $this->translate('Transaction will be deleted. Are you sure?'),
        'confirm_callback' => "function(link) { $.post($(link).attr('href'), {'transactions' : [{$this->transaction['id']}]}, function(){location.href='{$this->url('application/page', ['controller' => 'payments-administration', 'action' => 'list'], ['force_canonical' => true])}'}) }"
    ],
    [
        'controller' => 'payments-administration',
        'action' => 'view-transaction-items',
        'name' => $this->translate('View the transaction\'s items'),
        'check_acl' => true,
        'params' => [
            'slug' => $this->transaction['id']
        ]
    ]]
]))
?>

<!-- render a table with values -->
<?php $this->content = $this->partial('partial/table', [
    'headers' => [
    ],
    'list' => [
        'name' => [
            'first_name' => 'First Name',
            'name_value' => $this->transaction['first_name']
        ],
        'surname' => [
            'surname' => 'Last Name',
            'surname_value' => $this->transaction['last_name']
        ],
        'user_registered' => [
            'user_registered' => 'User registered',
            'user_registered_value' => $this->transaction['user_id']
        ],
        'email' => [
            'email' => 'Email',
            'email_value' => $this->transaction['email']
        ],
        'phone' => [
            'phone' => 'Phone',
            'phone_value' => $this->transaction['phone']
        ],
        'address' => [
            'address' => 'Address',
            'address_value' => $this->transaction['address']
        ],
        'date' => [
            'date' => 'Date',
            'date_value' => $this->transaction['date']
        ],
        'paid' => [
            'paid' => 'Paid',
            'paid_value' => $this->transaction['paid']
        ],
        'currency' => [
            'currency' => 'Currency',
            'currency_value' => $this->transaction['currency_code']
        ],
        'payment_type' => [
            'payment_type' => 'Payment type',
            'payment_type_value' => ($this->transaction['payment_description'] ? $this->translate($this->transaction['payment_description']) : '')
        ],
        'discount' => [
            'discount' => 'Discount',
            'discount_value' => ($this->transaction['discount_cupon'] ? $this->transaction['discount_cupon'] . '%' : '')
        ],
        'amount' => [
            'total_amount' => 'Total amount',
            'total_amount_value' => $this->paymentCostFormat([
                'cost' => $this->transaction['amount'],
                'currency' => $this->transaction['currency_code']
            ])
        ],
        'comments' => [
            'comments' => 'Comments',
            'comments_value' => $this->transaction['comments']
        ]
    ],
    'helpers' => [
        'first_name' => 'translate',
        'surname' => 'translate',
        'user_registered' => 'translate',
        'user_registered_value' => 'applicationBooleanValue',
        'email' => 'translate',
        'phone' => 'translate',
        'address' => 'translate',
        'date' => 'translate',
        'date_value' => 'applicationDate',
        'paid' => 'translate',
        'paid_value' => 'applicationBooleanValue',
        'currency' => 'translate',
        'payment_type' => 'translate',
        'discount' => 'translate',
        'total_amount' => 'translate',
        'comments' => 'translate'
    ]
]) ?>

<!-- notification -->
<?php echo $this->partial('partial/notification') ?>

<div class="row">
    <?php if ($this->extraActions): ?>
        <div class="col-md-4">
            <?php echo $this->extraActions ?>
        </div>
        <div class="col-md-8">
            <?php echo $this->partial('administration-partial/panel', [
                'title' => $this->translate('Details'),
                'body' => $this->content
            ]) ?>
        </div>
    <?php else: ?>
        <div class="col-md-12">
            <?php echo $this->partial('administration-partial/panel', [
                'title' => $this->translate('Details'),
                'body' => $this->content
            ]) ?>
        </div>
    <?php endif ?>
</div>