<?php $this->declareVars('content') ?>

<?php $this->content = $this->partial('partial/form', [
    'form' => $this->discount_form
]) ?>

<?php $this->placeholder('contentFooter')->captureStart() ?>
    <button type="button" id="popup-shopping-cart-submit" onclick="payment.sendDiscountCouponForm()" class="btn btn-primary">
        <?php echo $this->translate('Submit') ?>
    </button>
    <script type="text/javascript">
        $("#popup-shopping-cart-window").find("form:first").bind('submit', function() {
            payment.sendDiscountCouponForm();
            return false;
        });

        <?php if ($this->refresh_page) : ?>
            payment.hidePopupShopping();
            payment.refreshPage();
        <?php endif ?>
    </script>
<?php $this->placeholder('contentFooter')->captureEnd() ?>

<?php 
    echo $this->partial('partial/popup', [
        'popup_id' => 'popup-shopping-cart-window',
        'title' => 'Enter a discount code',
        'body' => $this->content,
        'footer' => $this->placeholder('contentFooter')
    ]) 
?>