<?php $this->declareVars('processedItems') ?>
<?php 
    $this->processedItems = $this->partial('partial/table', [
        'headers' => [
            'Title',
            'Unit Price',
            'Discount',
            'Count'
        ],
        'list' => $this->items,
        'helpers' => [
            'cost' => 'paymentProcessCost',
            'discount' => 'paymentProcessCost',
            'title' => 'paymentItemLink',
        ],
        'helpers_set_array' => [
            'title' => true
        ],
        'skipped_fields' => [
            'object_id',
            'countable',
            'handler',
            'page_name',
            'slug'
        ],
    ])
?>

<?php
    echo $this->partial('partial/popup', [
        'popup_id' => 'popup-transaction-items-window',
        'title' => 'Transaction items',
        'body' => $this->processedItems
    ])
?>